apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifecycle-demo-probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifecycle-demo-probes
  template:
    metadata:
      labels:
        app: lifecycle-demo-probes
    spec:
      containers:
        - name: app
          image: lifecycle-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /startup
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

