apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
spec:
  hard:
    pods: "20"
    requests.cpu: "5"
    requests.memory: 8Gi
    limits.cpu: "10"
    limits.memory: 16Gi
