apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-nodeport
  labels:
    app: hello-k8s
spec:
  type: NodePort
  selector:
    app: hello-k8s  # Must match your Deployment's pod label
  ports:
    - protocol: TCP
      port: 80          # Cluster-internal service port
      targetPort: 80    # Container port (Nginx)
      nodePort: 30080   # Optional fixed external port (between 30000–32767)
