apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifecycle-demo
  labels:
    app: lifecycle-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifecycle-demo
  template:
    metadata:
      labels:
        app: lifecycle-demo
    spec:
      containers:
        - name: app
          image: lifecycle-demo:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lifecycle-demo-svc
spec:
  selector:
    app: lifecycle-demo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
