apiVersion: v1
kind: Pod
metadata:
  name: besteffort-pod
  labels:
    app: resource-demo
spec:
  containers:
  - name: besteffort
    image: python:3.11-slim
    command: ["python", "-c"]
    args:
      - |
        import time
        # small allocation but no guaranteed resources
        a = ' ' * (50 * 1024 * 1024)
        time.sleep(3600)
