apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-pod
  labels:
    app: resource-demo
spec:
  containers:
  - name: guaranteed
    image: python:3.11-slim
    command: ["python", "-c"]
    args:
      - |
        # allocate a moderate buffer and sleep (keeps process resident)
        a = ' ' * (100 * 1024 * 1024)
        import time
        time.sleep(3600)
    resources:
      requests:
        cpu: "250m"
        memory: "200Mi"
      limits:
        cpu: "250m"
        memory: "200Mi"
