apiVersion: v1
kind: Namespace
metadata:
  name: resource-demo

---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-demo-limits
  namespace: resource-demo
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
